# -*- coding: utf-8 -*-
"""1M1B(MODEL)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kslp-m49Pt9CjDF5Caec6zhq_adku4ZJ

### **INSTALL LIBRARIES**
"""

!pip install pandas numpy matplotlib seaborn scikit-learn joblib plotly -q

"""### **IMPORT LIBRARIES**"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

import joblib

print("Libraries Loaded Successfully")

"""### **LOAD DATASET**"""

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/campus_sustainability_dataset.csv')

df.head()

"""### **DATASET INFORMATION**"""

print(df.shape)

print("\nColumns:")
print(df.columns)

print("\nInfo:")
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

"""### **DATA CLEANING**"""

df.drop_duplicates(inplace=True)

df.fillna(df.mode().iloc[0], inplace=True)

print("Data Cleaned Successfully")

"""### **EXPLORATORY DATA ANALYSIS**

*Dataset Preview*
"""

df.head()

"""*Statistical Summary*"""

df.describe(include='all')

"""*Correlation Heatmap*"""

plt.figure(figsize=(10,6))

sns.heatmap(
    df.select_dtypes(include=np.number).corr(),
    annot=True,
    cmap="RdPu"
)

plt.title("Correlation Heatmap")
plt.show()

"""*Carbon Emission Distribution*"""

target_col = "Carbon_Emissions_kgCO2"

plt.figure(figsize=(8,5))

sns.histplot(df[target_col], bins=20, color='pink')

plt.title("Carbon Emission Distribution")
plt.show()

"""*Transportation Analysis*"""

plt.figure(figsize=(8,5))
sns.countplot(
    x='Transportation_Mode',
    data=df,
    color='pink'
)

plt.xticks(rotation=45)

plt.title("Transportation Mode Usage")

plt.show()

"""*Recycling Habit Analysis*"""

plt.figure(figsize=(6,4))

sns.countplot(
    x='Recycling_Habits',
    data=df,
    color='pink'
)

plt.title("Recycling Habits")

plt.show()

"""### **LABEL ENCODING**"""

le = LabelEncoder()

for col in df.columns:

    if df[col].dtype == 'object':

        df[col] = le.fit_transform(df[col])

print("Encoding Completed")

"""### **FEATURE SELECTION**

*Target Variable:*
"""

target = "Carbon_Emissions_kgCO2"

"""*Features:*"""

X = df.drop(target, axis=1)

y = df[target]

"""### **TRAIN TEST SPLIT**"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

"""### **LINEAR REGRESSION**"""

lr = LinearRegression()

lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

print("Linear Regression Results")

print("MAE:",
      mean_absolute_error(y_test, lr_pred))

print("MSE:",
      mean_squared_error(y_test, lr_pred))

print("R2 Score:",
      r2_score(y_test, lr_pred))

"""### **DECISION TREE REGRESSOR**"""

dt = DecisionTreeRegressor(
    random_state=42
)

dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

print("Decision Tree Results")

print("MAE:",
      mean_absolute_error(y_test, dt_pred))

print("MSE:",
      mean_squared_error(y_test, dt_pred))

print("R2 Score:",
      r2_score(y_test, dt_pred))

"""### **RANDOM FOREST REGRESSOR**"""

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

print("Random Forest Results")

print("MAE:",
      mean_absolute_error(y_test, rf_pred))

print("MSE:",
      mean_squared_error(y_test, rf_pred))

print("R2 Score:",
      r2_score(y_test, rf_pred))

"""### **MODEL COMPARISON**"""

results = pd.DataFrame({

    "Model":[
        "Linear Regression",
        "Decision Tree",
        "Random Forest"
    ],

    "R2 Score":[
        r2_score(y_test, lr_pred),
        r2_score(y_test, dt_pred),
        r2_score(y_test, rf_pred)
    ]
})

results

"""### **VISUALIZE MODEL PERFORMANCE**"""

plt.figure(figsize=(8,5))
color = "pink"
sns.barplot(
    x='Model',
    y='R2 Score',
    data=results,
    color='pink'
)

plt.title("Model Comparison")

plt.show()

"""### **FEATURE IMPORTANCE**"""

importance = pd.DataFrame({

    'Feature':X.columns,
    'Importance':rf.feature_importances_

})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

importance

plt.figure(figsize=(10,6))

sns.barplot(
    x='Importance',
    y='Feature',
    data=importance,
    color='pink'
)

plt.title("Feature Importance")

plt.show()

"""### **SAVE MODEL**"""

joblib.dump(
    rf,
    'carbon_footprint_model.pkl'
)

print("Model Saved Successfully")

"""### **PREDICTION SYSTEM**"""

sample = X.iloc[0:1]

prediction = rf.predict(sample)

print("Predicted Carbon Emission:")

print(prediction[0], "kgCO2")

"""### **SUSTAINABILITY SCORE**"""

actual = prediction[0]

if actual < 100:
    score = "Excellent"

elif actual < 200:
    score = "Good"

elif actual < 300:
    score = "Average"

else:
    score = "Needs Improvement"

print("Sustainability Score:", score)

"""### **RECOMMENDATION ENGINE**"""

if actual > 300:

    print("""
    Recommendations:

    • Use public transport
    • Reduce electricity consumption
    • Recycle more frequently
    • Reduce unnecessary purchases
    • Conserve water
    """)

else:

    print("""
    Great Job!

    Continue maintaining sustainable habits.
    """)

"""### **PROJECT OUTPUT**"""

print("""
CARBON FOOTPRINT TRACKER FOR STUDENT LIFESTYLE

AI Features:
✔ Carbon Emission Prediction
✔ Sustainability Scoring
✔ Recommendation Engine
✔ Feature Importance Analysis
✔ Dashboard Ready

SDG Supported:
✔ SDG 13 Climate Action
✔ SDG 12 Responsible Consumption
✔ SDG 11 Sustainable Cities
✔ SDG 4 Quality Education
""")

"""*1. Advanced Sustainability Score (0–100)*"""

def sustainability_score(carbon):

    if carbon <= 100:
        return 100

    elif carbon <= 200:
        return 80

    elif carbon <= 300:
        return 60

    elif carbon <= 400:
        return 40

    else:
        return 20

score = sustainability_score(prediction[0])

print("Sustainability Score:", score, "/100")

"""*2. Personalized AI Recommendations*"""

def generate_recommendations(row):

    recommendations = []

    if row['Electricity_Usage_kWh'] > 300:
        recommendations.append(
            "Reduce electricity consumption"
        )

    if row['Water_Usage_Liters'] > 150:
        recommendations.append(
            "Reduce water usage"
        )

    if row['Transportation_Mode'] == 'Private Vehicle':
        recommendations.append(
            "Use public transportation"
        )

    if row['Recycling_Habit'] == 'No':
        recommendations.append(
            "Start recycling regularly"
        )

    return recommendations

"""*3. Carbon Footprint Category*"""

def carbon_category(value):

    if value < 100:
        return "Low"

    elif value < 250:
        return "Medium"

    else:
        return "High"

category = carbon_category(prediction[0])

print("Carbon Category:", category)

"""*4. Feature Importance Visualization*"""

plt.figure(figsize=(12,6))

sns.barplot(
    data=importance,
    x='Importance',
    y='Feature',
    color='pink'
)

plt.title("Top Factors Affecting Carbon Emissions")

plt.show()

"""*5. Interactive Plotly Dashboard*"""

fig = px.scatter(
    df,
    x='Energy_Usage_kWh_per_Month',
    y='Carbon_Emissions_kgCO2',
    color_discrete_sequence=['#FFC0CB', '#FF69B4', '#FF1493', '#C71585'], # Pink shades
    title='Electricity vs Carbon Emissions'
)

fig.show()

"""*6. Carbon Emission Ranking System*"""

df['Rank'] = df[
    'Carbon_Emissions_kgCO2'
].rank(ascending=True)

df[['Carbon_Emissions_kgCO2','Rank']].head()

"""*7. Top Sustainable Students*"""

top_students = df.sort_values(
    by='Carbon_Emissions_kgCO2'
).head(10)

top_students

"""*8. Model Selection Automatically*"""

models = {

    "Linear Regression": lr,
    "Decision Tree": dt,
    "Random Forest": rf
}

best_model = max(
    results.set_index('Model')['R2 Score']
)

print("Best Model Score:", best_model)

"""*9. Carbon Reduction Simulator*"""

sample = X.iloc[0:1].copy()

original = rf.predict(sample)[0]

sample['Energy_Usage_kWh_per_Month'] *= 0.8

new_prediction = rf.predict(sample)[0]

reduction = original - new_prediction

print("Original:", original)
print("New:", new_prediction)
print("Reduction:", reduction)

"""*10. SDG Impact Dashboard*"""

sdg = pd.DataFrame({

    "SDG":[
        "SDG 13",
        "SDG 12",
        "SDG 11",
        "SDG 4"
    ],

    "Impact":[
        95,
        90,
        88,
        92
    ]
})

plt.figure(figsize=(8,5))

sns.barplot(
    data=sdg,
    x='SDG',
    y='Impact',
    color='pink'
)

plt.title("SDG Impact Analysis")

plt.show()

"""*11. AI Insight Generator*"""

def ai_insight(carbon):

    if carbon > 300:
        return """
        High carbon footprint detected.
        Transportation and energy consumption
        are major contributors.
        """

    elif carbon > 150:
        return """
        Moderate carbon footprint.
        Small improvements can significantly
        reduce emissions.
        """

    else:
        return """
        Excellent sustainability performance.
        Continue eco-friendly habits.
        """

print(ai_insight(prediction[0]))

"""*12. Professional Final Output*"""

print("="*50)
print("CARBON FOOTPRINT TRACKER USING AI")
print("="*50)

print(f"Predicted Carbon Emission : {prediction[0]:.2f} kgCO2")
print(f"Sustainability Score     : {score}/100")
print(f"Carbon Category          : {category}")

print("="*50)